function J = Meiosis_GeoJac(gamma)

    t1 = gamma(1);
    t2 = gamma(2);
    t3 = gamma(3);
    t4 = gamma(4);
    t5 = gamma(5);
    t6 = gamma(6);
 
    J = [                                               cos(t6)*sin(t2)*sin(t3)*sin(t4) - cos(t2)*cos(t3)*cos(t6)*sin(t4) + cos(t2)*sin(t3)*sin(t5)*sin(t6) + cos(t3)*sin(t2)*sin(t5)*sin(t6) - cos(t2)*cos(t3)*cos(t4)*cos(t5)*sin(t6) + cos(t4)*cos(t5)*sin(t2)*sin(t3)*sin(t6),                                                                                                                                                                    cos(t4)*cos(t6) - cos(t5)*sin(t4)*sin(t6),                                                                                                                                                                                 cos(t4)*cos(t6) - cos(t5)*sin(t4)*sin(t6),                                                                                  sin(t5)*sin(t6),                                                                                                                                                                 cos(t6), 0;
                                                                                                                                                            cos(t2)*cos(t5)*sin(t3) + cos(t3)*cos(t5)*sin(t2) + cos(t2)*cos(t3)*cos(t4)*sin(t5) - cos(t4)*sin(t2)*sin(t3)*sin(t5),                                                                                                                                                                                              sin(t4)*sin(t5),                                                                                                                                                                                                           sin(t4)*sin(t5),                                                                                          cos(t5),                                                                                                                                                                       0, 1;
                                                        sin(t2)*sin(t3)*sin(t4)*sin(t6) - cos(t2)*cos(t6)*sin(t3)*sin(t5) - cos(t3)*cos(t6)*sin(t2)*sin(t5) - cos(t2)*cos(t3)*sin(t4)*sin(t6) + cos(t2)*cos(t3)*cos(t4)*cos(t5)*cos(t6) - cos(t4)*cos(t5)*cos(t6)*sin(t2)*sin(t3),                                                                                                                                                                    cos(t4)*sin(t6) + cos(t5)*cos(t6)*sin(t4),                                                                                                                                                                                 cos(t4)*sin(t6) + cos(t5)*cos(t6)*sin(t4),                                                                                 -cos(t6)*sin(t5),                                                                                                                                                                 sin(t6), 0;
          (12*cos(t5)*(cos(t1)*sin(t2)*sin(t3) - cos(t1)*cos(t2)*cos(t3)))/125 - (12*sin(t5)*(sin(t1)*sin(t4) - cos(t4)*(cos(t1)*cos(t2)*sin(t3) + cos(t1)*cos(t3)*sin(t2))))/125 - (13*cos(t1)*cos(t2))/50 + (27*cos(t1)*sin(t2)*sin(t3))/100 - (27*cos(t1)*cos(t2)*cos(t3))/100,  (sin(t1)*(130*sin(t2) + 135*cos(t2)*sin(t3) + 135*cos(t3)*sin(t2) + 48*cos(t2)*cos(t5)*sin(t3) + 48*cos(t3)*cos(t5)*sin(t2) + 48*cos(t2)*cos(t3)*cos(t4)*sin(t5) - 48*cos(t4)*sin(t2)*sin(t3)*sin(t5)))/500, (12*cos(t5)*(cos(t2)*sin(t1)*sin(t3) + cos(t3)*sin(t1)*sin(t2)))/125 + (27*cos(t2)*sin(t1)*sin(t3))/100 + (27*cos(t3)*sin(t1)*sin(t2))/100 - (12*cos(t4)*sin(t5)*(sin(t1)*sin(t2)*sin(t3) - cos(t2)*cos(t3)*sin(t1)))/125, (12*sin(t5)*(cos(t1)*cos(t4) - sin(t4)*(cos(t2)*sin(t1)*sin(t3) + cos(t3)*sin(t1)*sin(t2))))/125, (12*cos(t5)*(cos(t1)*sin(t4) + cos(t4)*(cos(t2)*sin(t1)*sin(t3) + cos(t3)*sin(t1)*sin(t2))))/125 - (12*sin(t5)*(sin(t1)*sin(t2)*sin(t3) - cos(t2)*cos(t3)*sin(t1)))/125, 0;
          (12*sin(t5)*(cos(t1)*sin(t4) + cos(t4)*(cos(t2)*sin(t1)*sin(t3) + cos(t3)*sin(t1)*sin(t2))))/125 - (13*cos(t2)*sin(t1))/50 + (12*cos(t5)*(sin(t1)*sin(t2)*sin(t3) - cos(t2)*cos(t3)*sin(t1)))/125 + (27*sin(t1)*sin(t2)*sin(t3))/100 - (27*cos(t2)*cos(t3)*sin(t1))/100, -(cos(t1)*(130*sin(t2) + 135*cos(t2)*sin(t3) + 135*cos(t3)*sin(t2) + 48*cos(t2)*cos(t5)*sin(t3) + 48*cos(t3)*cos(t5)*sin(t2) + 48*cos(t2)*cos(t3)*cos(t4)*sin(t5) - 48*cos(t4)*sin(t2)*sin(t3)*sin(t5)))/500, (12*cos(t4)*sin(t5)*(cos(t1)*sin(t2)*sin(t3) - cos(t1)*cos(t2)*cos(t3)))/125 - (12*cos(t5)*(cos(t1)*cos(t2)*sin(t3) + cos(t1)*cos(t3)*sin(t2)))/125 - (27*cos(t1)*cos(t2)*sin(t3))/100 - (27*cos(t1)*cos(t3)*sin(t2))/100, (12*sin(t5)*(cos(t4)*sin(t1) + sin(t4)*(cos(t1)*cos(t2)*sin(t3) + cos(t1)*cos(t3)*sin(t2))))/125, (12*cos(t5)*(sin(t1)*sin(t4) - cos(t4)*(cos(t1)*cos(t2)*sin(t3) + cos(t1)*cos(t3)*sin(t2))))/125 + (12*sin(t5)*(cos(t1)*sin(t2)*sin(t3) - cos(t1)*cos(t2)*cos(t3)))/125, 0;
                                                                                                                                                                                                                                                                            0,                                                              (27*cos(t2 + t3))/100 + (13*cos(t2))/50 + (6*sin(t4 - t5)*sin(t2 + t3))/125 - (6*sin(t2 + t3)*sin(t4 + t5))/125 + (12*cos(t2 + t3)*cos(t5))/125,                                                                                                                             (27*cos(t2 + t3))/100 + (12*cos(t2 + t3)*cos(t5))/125 - (12*sin(t2 + t3)*cos(t4)*sin(t5))/125,                                                           -(12*cos(t2 + t3)*sin(t4)*sin(t5))/125,                                                                                                   (12*cos(t2 + t3)*cos(t4)*cos(t5))/125 - (12*sin(t2 + t3)*sin(t5))/125, 0];

end